// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: scrape_data.proto

package model

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsiderTransaction_TransactionType int32

const (
	InsiderTransaction_OTHER       InsiderTransaction_TransactionType = 0
	InsiderTransaction_BUY         InsiderTransaction_TransactionType = 1
	InsiderTransaction_SELL        InsiderTransaction_TransactionType = 2
	InsiderTransaction_DISPOSITION InsiderTransaction_TransactionType = 3
)

// Enum value maps for InsiderTransaction_TransactionType.
var (
	InsiderTransaction_TransactionType_name = map[int32]string{
		0: "OTHER",
		1: "BUY",
		2: "SELL",
		3: "DISPOSITION",
	}
	InsiderTransaction_TransactionType_value = map[string]int32{
		"OTHER":       0,
		"BUY":         1,
		"SELL":        2,
		"DISPOSITION": 3,
	}
)

func (x InsiderTransaction_TransactionType) Enum() *InsiderTransaction_TransactionType {
	p := new(InsiderTransaction_TransactionType)
	*p = x
	return p
}

func (x InsiderTransaction_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InsiderTransaction_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_scrape_data_proto_enumTypes[0].Descriptor()
}

func (InsiderTransaction_TransactionType) Type() protoreflect.EnumType {
	return &file_scrape_data_proto_enumTypes[0]
}

func (x InsiderTransaction_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InsiderTransaction_TransactionType.Descriptor instead.
func (InsiderTransaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_scrape_data_proto_rawDescGZIP(), []int{0, 0}
}

type InsiderTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionTime *timestamp.Timestamp               `protobuf:"bytes,1,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	InsiderName     string                             `protobuf:"bytes,2,opt,name=insider_name,json=insiderName,proto3" json:"insider_name,omitempty"`
	TransactionType InsiderTransaction_TransactionType `protobuf:"varint,3,opt,name=transaction_type,json=transactionType,proto3,enum=InsiderTransaction_TransactionType" json:"transaction_type,omitempty"`
}

func (x *InsiderTransaction) Reset() {
	*x = InsiderTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scrape_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsiderTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsiderTransaction) ProtoMessage() {}

func (x *InsiderTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_scrape_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsiderTransaction.ProtoReflect.Descriptor instead.
func (*InsiderTransaction) Descriptor() ([]byte, []int) {
	return file_scrape_data_proto_rawDescGZIP(), []int{0}
}

func (x *InsiderTransaction) GetTransactionTime() *timestamp.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *InsiderTransaction) GetInsiderName() string {
	if x != nil {
		return x.InsiderName
	}
	return ""
}

func (x *InsiderTransaction) GetTransactionType() InsiderTransaction_TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return InsiderTransaction_OTHER
}

var File_scrape_data_proto protoreflect.FileDescriptor

var file_scrape_data_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x02, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x10, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4e, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x23, 0x2e, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x49, 0x53, 0x50, 0x4f, 0x53,
	0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x74, 0x65, 0x72, 0x62, 0x65, 0x61, 0x6d, 0x69,
	0x73, 0x68, 0x2f, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_scrape_data_proto_rawDescOnce sync.Once
	file_scrape_data_proto_rawDescData = file_scrape_data_proto_rawDesc
)

func file_scrape_data_proto_rawDescGZIP() []byte {
	file_scrape_data_proto_rawDescOnce.Do(func() {
		file_scrape_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_scrape_data_proto_rawDescData)
	})
	return file_scrape_data_proto_rawDescData
}

var file_scrape_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scrape_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scrape_data_proto_goTypes = []interface{}{
	(InsiderTransaction_TransactionType)(0), // 0: InsiderTransaction.TransactionType
	(*InsiderTransaction)(nil),              // 1: InsiderTransaction
	(*timestamp.Timestamp)(nil),             // 2: google.protobuf.Timestamp
}
var file_scrape_data_proto_depIdxs = []int32{
	2, // 0: InsiderTransaction.transaction_time:type_name -> google.protobuf.Timestamp
	0, // 1: InsiderTransaction.transaction_type:type_name -> InsiderTransaction.TransactionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scrape_data_proto_init() }
func file_scrape_data_proto_init() {
	if File_scrape_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scrape_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsiderTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scrape_data_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scrape_data_proto_goTypes,
		DependencyIndexes: file_scrape_data_proto_depIdxs,
		EnumInfos:         file_scrape_data_proto_enumTypes,
		MessageInfos:      file_scrape_data_proto_msgTypes,
	}.Build()
	File_scrape_data_proto = out.File
	file_scrape_data_proto_rawDesc = nil
	file_scrape_data_proto_goTypes = nil
	file_scrape_data_proto_depIdxs = nil
}
